server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Reverse Proxy for Microservices (Production)
    location /api/profile {
        proxy_pass http://profile-service:8081;
    }
    location /api/projects {
        proxy_pass http://projects-service:8082;
    }
    location /api/resume {
        proxy_pass http://resume-service:8083;
    }
    location /api/certificates {
        proxy_pass http://certificates-service:8084;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
