server.port=8084
spring.application.name=certificates-service
spring.data.mongodb.uri=mongodb://mongo:27017/certificates_db
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
